### ISSUE TITLE
msmbstyle 0.0.9 + bookdown 0.1 problems

### ISSUE THREAD

**Issue by aridus** [grimbough/msmbstyle#16]
Good day

I have updated to msmbstyle 0.0.9 with bookdown 0.1 and there are two problems (illustrated here with msmbstyle-master):

1) The header is not present:
![Screenshot from 2019-05-11 05-51-59](https://user-images.githubusercontent.com/11365547/57565203-5856cd00-73b1-11e9-8d1d-5f61049315d0.png)

2) Code chunks run in to the margin (i.e. the bottom slider does not appear):
![Screenshot from 2019-05-11 05-52-36](https://user-images.githubusercontent.com/11365547/57565216-7de3d680-73b1-11e9-8058-0ac36228856b.png)

Would it be possible for you to look into these matters? Our new website (with a book prepared in msmbstyle embedded) is due to go live in the next 1-2 weeks and it would be very helpful if you could find time to look at this).

With grateful thanks.

**Comment by grimbough** [comment]
Thanks for the report. I'd noticed this rebuilding our book too. It's a top priority for me, should be done early next week. It'll include an update to the CSS for blockquotes too.

**Comment by aridus** [comment]
Fantastic, thank you: much appreciated!

**Comment by aridus** [comment]
I see that the header problem is now fixed, thank you!

**Comment by grimbough** [comment]
Is the code running into the margin fixed too?  That was introduced by a change in bookdown that broke my CSS, but I'm hoping it's sorted now.

**Comment by aridus** [comment]
Unfortunately it still runs into the margin:

![Screenshot from 2019-05-17 12-22-26](https://user-images.githubusercontent.com/11365547/57924954-7daa7600-789e-11e9-9db6-503ba622bab6.png)

**Comment by grimbough** [comment]
I think I'd address this locally and not pushed it to Github.  Try updating the package and rebuilding.

**Comment by aridus** [comment]
Thank you. The grey box is now ok (it doesn't extend into the margin, but the code still does:

![Screenshot from 2019-05-17 15-24-25](https://user-images.githubusercontent.com/11365547/57934567-e81be000-78b7-11e9-93ba-982dcb234b75.png)

**Comment by grimbough** [comment]
Weird, for me it looks ok: 

![image](https://user-images.githubusercontent.com/971237/57935885-181cb080-78c3-11e9-91b1-6a58b3981afd.png)

What browser are you working in? I'm using Chrome. The text overflow behaviour was set to `auto` so maybe that's different between browsers.  I've explicitly set it to scrolling now, so give that a whirl.

**Comment by aridus** [comment]
I am using Chrome and Firefox on Ubunut - same problem on both. However, the latest update resolves this issue:

![Screenshot from 2019-05-17 15-51-31](https://user-images.githubusercontent.com/11365547/57936382-bc025e00-78bb-11e9-8729-a5e41b6922d1.png)

Thanks again.
