### ISSUE TITLE
Acknowledgement of msmbstyle and author

### ISSUE THREAD

**Issue by aridus** [grimbough/msmbstyle#18]
In my forthcoming Writing for Conservation guide, I acknowledge msmbstyle in the following way, in the Preface (note link through to the github page):

![Screenshot from 2019-05-14 19-14-33](https://user-images.githubusercontent.com/11365547/57721631-989da000-767c-11e9-9c49-364955246bde.png)

I would also be happy to acknowledge the author by name, if you feel that is appropriate. Could you kindly let me know?

With thanks.

**Comment by grimbough** [comment]
That acknowledgement is fine with me.  Having one name probably means you should have names for bookdown etc too, and I expect that would be clunky to read.

If you could let me have a link to the book once it's available, that would be great to put on the Github page here as another example of what can be produced.

**Comment by aridus** [comment]
Many thanks. I will send you a link to the manual - which will be embedded in our website - in a few weeks.

**Comment by aridus** [comment]
I am  happy to let you know that my guide, which is formatted with the great msmbstyle, is now available on our new website [https://www.oryxthejournal.org/](https://www.oryxthejournal.org/). Thank you very much for help along the way!

To jump directly to the guide: [https://www.oryxthejournal.org/writing-for-conservation-guide/present-your-data.html](https://www.oryxthejournal.org/writing-for-conservation-guide/present-your-data.html)

This is something of a first draft (more material will be added in time). 

One outstanding matter is the presentation of the tables, which I would like to improve (see [this issue](https://github.com/grimbough/msmbstyle/issues/21#issue-453762404)).
