### ISSUE TITLE
position of margin table

### ISSUE THREAD

**Issue by Zhengguo-Xu** [grimbough/msmbstyle#20]
Many thanks for such a great package! 

I noticed that the position of the margin table is not aligned with the main text where it was referenced, especially when `echo = TRUE` is set in knitr trunk option. If the code is long, the table will be put way too low. Is there anything we can do to move it up?

 Use your example at https://www-huber.embl.de/users/msmith/msmbstyle/tables.html#tab:margin-table, can we move the margin table 1.2 up to the same height of the sentence "You can also include tables in the margin column as in Table 1.2, with the caption above" ? or at least to the same height of the first line of the echoed code `(HIV <- data.frame(Patient = ... )` ?

**Comment by grimbough** [comment]
My feeling was that most of the time if you're producing a table, you probably don't want to show code that renders the table, so it would appear alongside the next paragraph.  The code is shown in that example only because it's an example, but perhaps you have a different use case.

I'll see if I can copy the tufte approach to positioning the margin images, so that margin tables appear inline with the code chunk that produced them.  This shouldn't affect the output if the code is hidden, but will line up better if it is.

**Comment by Zhengguo-Xu** [comment]
Thanks! You're absolutely right. In most cases the code won't be shown in the final document. In my case, it was meant for complete R newbie to use R and it would be a good idea to show all code including those making tables so they can understand it better.  

In short, it's for educational use.  Maybe others will have different purpose to show the code for table as well. though I couldn't think of any currently.

**Comment by Zhengguo-Xu** [comment]
I noticed that the package is now 0.0.10. Thanks. 

However, I got the following error message when compile the example files:

```
Error in xml_add_sibling(code, caption, .where = "before", .copy = FALSE) : 
  could not find function "xml_add_sibling"
Calls: <Anonymous> ... <Anonymous> -> split_chapters -> build -> .move_margin_table
In addition: Warning messages:
1: In citation(pkg, auto = if (pkg == "base") NULL else TRUE) :
  no date field in DESCRIPTION file of package 'msmbstyle'
2: In citation(pkg, auto = if (pkg == "base") NULL else TRUE) :
  could not determine year for 'msmbstyle' from package DESCRIPTION file
3: The label(s) ques:fail not found 
Please delete main.Rmd after you finish debugging the error.
Execution halted

Exited with status 1.
```
I didn't see the definition of this function in the source file but it was used inside the `.move_margin_table` function.  Is there any other package that I need to install to have the function `xml_add_sibling` working?

**Comment by grimbough** [comment]
That function is in the `xml2` package, but I'd forgotten to update the NAMESPACE.  It should be working now.

**Comment by Zhengguo-Xu** [comment]
Works like a charm in my PC with Linux system! I'll test it in my work laptop with Windows system tomorrow. I'm sure there won't any problems. Many thanks!
