### ISSUE TITLE
References in the margins

### ISSUE THREAD

**Issue by lgatto** [grimbough/msmbstyle#9]
I am working on two different computers. The `margin_references: TRUE` output is set in my `index.Rmd` and the references appear in margins only on my laptop only, not on my desktop. 
I assume this is because of a missing (system?) dependency but I fail to identify which one. 

Any help much appreciated.

**Comment by grimbough** [comment]
This sounds weird, I'm not aware of any dependencies that should do this but much of the underlying code is rmarkdown/bookdown/tufte so there's a chance I've missed something.

Do the references appear elsewhere on the desktop, or are the missing entirely?  I guess you've already checked you've got the same package versions - I've made some changes recently but it shouldn't affect references, unless the CSS is floating them off the page somewhere.

**Comment by lgatto** [comment]
The references are present at the end - everything looks fine, except they aren't printed in the margins. I also checked that my `pandoc-citeproc` was recent enough (which I think it is with version 0.16.1.2) - it is however 0.10.5.1 on my laptop (that's where the refs are in the margins). What version do you have?

`msmbstyle` versions match between the two computers. 

It's very weird indeed. I will try to investigate further and report back if I find anything.

**Comment by grimbough** [comment]
I'm using version 0.10.4 which ships with Rstudio 1.1.463.
